### ISSUE TITLE
Is this/does this have to be Hugo-specific?

### ISSUE THREAD

**Issue by vassudanagunta** [lpar/hugoutil#1]
Markdown and YAML front matter aren't specific to Hugo.

There are a lot of authors out there not using Hugo who might love this.

I recommend removing any Hugo dependencies (If there is some useful Hugo-specific behavior, it could be enabled with a CLI switch or automatically happen if the tool detects its operating on Markdown in a Hugo content folder).

I haven't used it yet, but seems like a great tool. Thanks!

**Comment by lpar** [comment]
Right now it operates on Markdown files with a YAML or TOML frontmatter. It expects the headers to be `title`, `categories` and `tags`, but other than that there's nothing specific to Hugo in it and it doesn't use any of Hugo's library code. However, I have no idea what other systems it might be useful for given what it does. Ghost perhaps?

**Comment by vassudanagunta** [comment]
Sorry, my mistake. Not as general as I thought. I was thinking it was a general purpose YAML front matter manipulator. e.g. a tool that could do things like: *For a given front matter field, replace all values of "x" with "y", including when Y in a list of values.*

**Comment by lpar** [comment]
No, it's deliberately not designed to be completely general, because that would make the command line annoying. I definitely didn't want it to end up like `metaflac`, for example, where adding and removing tags requires an annoying and long-winded command syntax, as well as remembering the field names.
